### ISSUE TITLE
Error: C stack usage in FST calculation

### ISSUE THREAD

**Issue by Flavjack** [hemstrow/snpR#71]
Hi @hemstrow ,

Recently when I tried to calculate the FST, the software was not able to give results, 

```
snpdt_filt <- calc_pairwise_fst(snpdt_filt, facets = "cross"
                               , boot_par = ncores # 6
                               , verbose = T
                               )
```
Results:

> Collating results...Error: C stack usage  15926928 is too close to the limit

Would you know how I can solve this issue? Thanks

**Comment by hemstrow** [comment]
Hey @Flavjack ,

As far as I am aware, C stack usage errors are usually due recursions in code going too deep, which I *shouldn't* be a thing with snpR, since it only ever does a few levels of recursion. I do think R's `merge` function does some recursion, though, which is called internally pretty frequently and might be to blame? If you'd like to send me a small sample of your dataset, say 10000 random SNPs, I can try and diagnose. You can subset your snpR object with something like:

```{r}
sub <- sample(10000, snpdt_filt, FALSE)
sub <- snpdt_filt[sub,]
saveRDS(sub, "subset_snpRdata.RDS")
```
then email me the subset data at hemstrow@gmail.com (or attach it here in a response to the github issue, if you are OK with that).

Another thing you could try is increasing your C stack limit a bit. You can't do that with R directly as far as I know (see [this thread](https://stackoverflow.com/questions/14719349/error-c-stack-usage-is-too-close-to-the-limit)), but it might fix the issue. Another thing you could try is restarting your R session/server/etc, since I've seen some mentions of that error being fixed by doing so.

Best,
Will

**Comment by hemstrow** [comment]
Marked as closed with no reply; feel free to reply if you have more questions, @Flavjack !

**Comment by hemstrow** [comment]
Hey @gfwalker ,

I believe this bug is fixed in the most recent version (dev or master). 

It was due to an update to `data.table` which caused infinite recursion when converting from an empty `data.frame` if and only if that `data.frame` was instantiated as part of an s4 object slot. Weird!

Please let me know if you have any issues after updating, and I can take another look!

**Comment by gfwalker** [comment]
Thank you for the quick response! Unfortunately, I am on the newest version 1.2.11 and still receiving the error with the same traceback() output. I also tried the dev version 1.2.12.9999 with the same result.

**Comment by hemstrow** [comment]
Ok, I'll take another look then! Thanks for verifying the version. If I can reproduce it I'll try and get it fixed today.

**Comment by hemstrow** [comment]
Just to confirm @gfwalker, if you run `utils::packageVersion("snpR")`, it should say 1.2.12, correct? That's the current master branch veersion; I just realized that the readme lists the wrong version number. If you are on 1.2.12 and still having the bug, could you:

A) Run  `utils::packageVersion("data.table")` and tell me what version you have?
B) Share a small subset of your data with me which produces the same error? You can either attach it here or email it to me at hemstrow@gmail.com, whichever you'd prefer.

I've been unable to reproduce it with my data, so that'd be helpful in getting the bug fixed.

**Comment by hemstrow** [comment]
Update--works fine on newest R versions, error was on R 4.3.2
